//  interface FIAT{
//     symbol:String;
//     logoURI:String;
//     describe:String;
//     sign:String;
// }
export declare class FIAT {
    readonly symbol: string;
    readonly logoURI: string;
    readonly describe: string;
    readonly sign: string;
    protected constructor(symbol: string, logoURI: string, sign: string, describe: string);
}
const ALLFIAT: FIAT[] = [
    { logoURI: "https://www.xe.com/static-images/cny.static.b5710fca4cc33e583970ae4944a552f1.svg", symbol: "CNY", sign: "CNY", describe: "Chinese Yuan Renminbi" },
    { logoURI: "https://www.xe.com/static-images/usd.static.e8b657d1161a08a32415d284a8e1dc89.svg", symbol: "USD", sign: "USD", describe: "US Dollar" },
    { logoURI: "images/WHYK.png", symbol: "HYK", sign: "HYK", describe: "Hayek" },
  
    {
        symbol: "USDT(ETH)",
        logoURI: "./images/USDT.png",
        describe: "USDT on Ethererum",
        sign: "USDT"
    },
    {
        symbol: "USDT(HAYKE)",
        logoURI: "./images/USDT.png",
        describe: "USDT on HAYEK",
        sign: "USDT"
    },
    {
        symbol: "USDT(OEC)",
        logoURI: "./images/USDT.png",
        describe: "USDT on OKEx Chain",
        sign: "USDT"
    },
    {
        symbol: "USDT(BSC)",
        logoURI: "./images/USDT.png",
        describe: "USDT on Binance smart chain",
        sign: "USDT"
    },

    {
        symbol: "USDT(HECO)",
        logoURI: "./images/USDT.png",
        describe: "USDT on HECO",
        sign: "USDT"
    },
   
    { logoURI: "https://www.xe.com/static-images/eur.static.7c6f881c3b6506b03bcbda3644485094.svg", symbol: "EUR", sign: "EUR", describe: "Euro" },
    { logoURI: "https://www.xe.com/static-images/gbp.static.da0ca3d1b6d9e74642276a0ea3cde603.svg", symbol: "GBP", sign: "GBP", describe: "British Pound" },
    { logoURI: "https://www.xe.com/static-images/cad.static.0bfb6a6d0adf4f3b1c28c0c90248b18b.svg", symbol: "CAD", sign: "CAD", describe: "Canadian Dollar" },
    { logoURI: "https://www.xe.com/static-images/aud.static.6e69da30d2a4593d811f765c491964af.svg", symbol: "AUD", sign: "AUD", describe: "Australian Dollar" },
    { logoURI: "https://www.xe.com/static-images/jpy.static.238642084e415a2c2304c9b3da2308d9.svg", symbol: "JPY", sign: "JPY", describe: "Japanese Yen" },
    { logoURI: "https://www.xe.com/static-images/aed.static.93a2e850c3b1ada8d436ede89073d8ac.svg", symbol: "AED", sign: "AED", describe: "Emirati Dirham" },
    { logoURI: "https://www.xe.com/static-images/afn.static.fc040a374b2f46a681642a23a82f7790.svg", symbol: "AFN", sign: "AFN", describe: "Afghan Afghani" },
    { logoURI: "https://www.xe.com/static-images/all.static.e7a0c811b96576ed15ca79f4e07cdea1.svg", symbol: "ALL", sign: "ALL", describe: "Albanian Lek" },
    { logoURI: "https://www.xe.com/static-images/amd.static.3db1d014db3fadc8abbf7f446562d7d7.svg", symbol: "AMD", sign: "AMD", describe: "Armenian Dram" },
    { logoURI: "https://www.xe.com/static-images/ang.static.f8f890eaf724539eb7f7323455445f43.svg", symbol: "ANG", sign: "ANG", describe: "Dutch Guilder" },
    { logoURI: "https://www.xe.com/static-images/aoa.static.cd7cee2a6cb78c4cf595edcb1d373f74.svg", symbol: "AOA", sign: "AOA", describe: "Angolan Kwanza" },
    { logoURI: "https://www.xe.com/static-images/ars.static.336f9b59f016468d2b5d19c00a691876.svg", symbol: "ARS", sign: "ARS", describe: "Argentine Peso" },
    { logoURI: "https://www.xe.com/static-images/aud.static.6e69da30d2a4593d811f765c491964af.svg", symbol: "AUD", sign: "AUD", describe: "Australian Dollar" },
    { logoURI: "https://www.xe.com/static-images/awg.static.033ca802e4276b57b69e3ed7f0c81ed3.svg", symbol: "AWG", sign: "AWG", describe: "Aruban or Dutch Guilder" },
    { logoURI: "https://www.xe.com/static-images/azn.static.398383ae20afacdb74d476b8a881545b.svg", symbol: "AZN", sign: "AZN", describe: "Azerbaijan Manat" },
    { logoURI: "https://www.xe.com/static-images/bam.static.dc4fa891e4e64be6cfcdc8345e10142f.svg", symbol: "BAM", sign: "BAM", describe: "Bosnian Convertible Mark" },
    { logoURI: "https://www.xe.com/static-images/bbd.static.760b046fbd5f8609126ad2db46148c4f.svg", symbol: "BBD", sign: "BBD", describe: "Barbadian or Bajan Dollar" },
    { logoURI: "https://www.xe.com/static-images/bdt.static.3a5be3895a8739cf15358a469aefaf8f.svg", symbol: "BDT", sign: "BDT", describe: "Bangladeshi Taka" },
    { logoURI: "https://www.xe.com/static-images/bgn.static.13c846b32c10f098953fed3ac5d3cdf4.svg", symbol: "BGN", sign: "BGN", describe: "Bulgarian Lev" },
    { logoURI: "https://www.xe.com/static-images/bhd.static.1383834e97690952aa4f128aff997809.svg", symbol: "BHD", sign: "BHD", describe: "Bahraini Dinar" },
    { logoURI: "https://www.xe.com/static-images/bif.static.c6c594d53e7d017bf08b1337824a450a.svg", symbol: "BIF", sign: "BIF", describe: "Burundian Franc" },
    { logoURI: "https://www.xe.com/static-images/bmd.static.b8bb62b41d310fe2d8fd804ab48b56c6.svg", symbol: "BMD", sign: "BMD", describe: "Bermudian Dollar" },
    { logoURI: "https://www.xe.com/static-images/bnd.static.0ca0f6a3b027665fb5e6764cfd0fba27.svg", symbol: "BND", sign: "BND", describe: "Bruneian Dollar" },
    { logoURI: "https://www.xe.com/static-images/bob.static.8de1a62cb60de5f1f89dcede76b6dc7a.svg", symbol: "BOB", sign: "BOB", describe: "Bolivian Bolíviano" },
    { logoURI: "https://www.xe.com/static-images/brl.static.9fd0e9a45b21d778b09f62837fafd607.svg", symbol: "BRL", sign: "BRL", describe: "Brazilian Real" },
    { logoURI: "https://www.xe.com/static-images/bsd.static.148fc4ed1f4096128442b267cce368a9.svg", symbol: "BSD", sign: "BSD", describe: "Bahamian Dollar" },
    { logoURI: "https://www.xe.com/static-images/btn.static.b81d09635d9efa6e7daaac1bbac9fef0.svg", symbol: "BTN", sign: "BTN", describe: "Bhutanese Ngultrum" },
    { logoURI: "https://www.xe.com/static-images/bwp.static.28a1278ae5bae186e0967d55af5e189e.svg", symbol: "BWP", sign: "BWP", describe: "Botswana Pula" },
    { logoURI: "https://www.xe.com/static-images/byn.static.96a11728517530e0779f350d7ae16f7d.svg", symbol: "BYN", sign: "BYN", describe: "Belarusian Ruble" },
    { logoURI: "https://www.xe.com/static-images/byr.static.96a11728517530e0779f350d7ae16f7d.svg", symbol: "BYR", sign: "BYR", describe: "Belarusian Ruble" },
    { logoURI: "https://www.xe.com/static-images/bzd.static.846ac0cb479ab658c5cbe80c555ef53f.svg", symbol: "BZD", sign: "BZD", describe: "Belizean Dollar" },
    { logoURI: "https://www.xe.com/static-images/cad.static.0bfb6a6d0adf4f3b1c28c0c90248b18b.svg", symbol: "CAD", sign: "CAD", describe: "Canadian Dollar" },
    { logoURI: "https://www.xe.com/static-images/cdf.static.ed4d1bc96bed2bfd11a8738fefeca1ce.svg", symbol: "CDF", sign: "CDF", describe: "Congolese Franc" },
    { logoURI: "https://www.xe.com/static-images/chf.static.eb65ed7418d2ad8703a7c9c54467b785.svg", symbol: "CHF", sign: "CHF", describe: "Swiss Franc" },
    { logoURI: "https://www.xe.com/static-images/clp.static.c4f3a6780feb5a8c6eddb7c5fbc49298.svg", symbol: "CLP", sign: "CLP", describe: "Chilean Peso" },
    { logoURI: "https://www.xe.com/static-images/cop.static.b8c0df9825b439abb5f9ca9ef09b42f3.svg", symbol: "COP", sign: "COP", describe: "Colombian Peso" },
    { logoURI: "https://www.xe.com/static-images/crc.static.fc1c305b5f981ca2b847d92161b1da99.svg", symbol: "CRC", sign: "CRC", describe: "Costa Rican Colon" },
    { logoURI: "https://www.xe.com/static-images/cuc.static.82c0ab834c7a3be607b4086dad4ce77d.svg", symbol: "CUC", sign: "CUC", describe: "Cuban Convertible Peso" },
    { logoURI: "https://www.xe.com/static-images/cup.static.82c0ab834c7a3be607b4086dad4ce77d.svg", symbol: "CUP", sign: "CUP", describe: "Cuban Peso" },
    { logoURI: "https://www.xe.com/static-images/cve.static.ed5bcc3d32d77c6ea7329e7c3a711ede.svg", symbol: "CVE", sign: "CVE", describe: "Cape Verdean Escudo" },
    { logoURI: "https://www.xe.com/static-images/czk.static.17bc9a9c46431f9929da881afadebb1b.svg", symbol: "CZK", sign: "CZK", describe: "Czech Koruna" },
    { logoURI: "https://www.xe.com/static-images/djf.static.dd77cdbb27f198455fb61d0ac88ff142.svg", symbol: "DJF", sign: "DJF", describe: "Djiboutian Franc" },
    { logoURI: "https://www.xe.com/static-images/dkk.static.205755395f9a114d6bc30c8082d9d659.svg", symbol: "DKK", sign: "DKK", describe: "Danish Krone" },
    { logoURI: "https://www.xe.com/static-images/dop.static.7983884e2e9bb93fb60bb0c0e19ad977.svg", symbol: "DOP", sign: "DOP", describe: "Dominican Peso" },
    { logoURI: "https://www.xe.com/static-images/dzd.static.331fea446a59ffde62fe78aef005a62a.svg", symbol: "DZD", sign: "DZD", describe: "Algerian Dinar" },
    { logoURI: "https://www.xe.com/static-images/eek.static.8bcd7f0c6328cd7748f77294eebd1d6d.svg", symbol: "EEK", sign: "EEK", describe: "Estonian Kroon" },
    { logoURI: "https://www.xe.com/static-images/egp.static.df88137050e409e79db3433d9c8b1493.svg", symbol: "EGP", sign: "EGP", describe: "Egyptian Pound" },
    { logoURI: "https://www.xe.com/static-images/ern.static.82e9ec91d81f7a6aa1be010fc2dab9fe.svg", symbol: "ERN", sign: "ERN", describe: "Eritrean Nakfa" },
    { logoURI: "https://www.xe.com/static-images/etb.static.925a7e101de6e89372f7d4099f56bb19.svg", symbol: "ETB", sign: "ETB", describe: "Ethiopian Birr" },
    { logoURI: "https://www.xe.com/static-images/eur.static.7c6f881c3b6506b03bcbda3644485094.svg", symbol: "EUR", sign: "EUR", describe: "Euro" },
    { logoURI: "https://www.xe.com/static-images/fjd.static.fdf5b1476a3bddb186a2fd0aad645141.svg", symbol: "FJD", sign: "FJD", describe: "Fijian Dollar" },
    { logoURI: "https://www.xe.com/static-images/fkp.static.ea26b7341bd950b0756e2eebbf163149.svg", symbol: "FKP", sign: "FKP", describe: "Falkland Island Pound" },
    { logoURI: "https://www.xe.com/static-images/gbp.static.da0ca3d1b6d9e74642276a0ea3cde603.svg", symbol: "GBP", sign: "GBP", describe: "British Pound" },
    { logoURI: "https://www.xe.com/static-images/gel.static.849571d9c2a98fd1f8063ec10be0fbb1.svg", symbol: "GEL", sign: "GEL", describe: "Georgian Lari" },
    { logoURI: "https://www.xe.com/static-images/ggp.static.9f7268704541cecd25e6582afd0c0dc1.svg", symbol: "GGP", sign: "GGP", describe: "Guernsey Pound" },
    { logoURI: "https://www.xe.com/static-images/ghs.static.2fd2dae253aca35d0d1f8e3628b79246.svg", symbol: "GHS", sign: "GHS", describe: "Ghanaian Cedi" },
    { logoURI: "https://www.xe.com/static-images/gip.static.76dd9898bd18361baa44ec65c2b6265a.svg", symbol: "GIP", sign: "GIP", describe: "Gibraltar Pound" },
    { logoURI: "https://www.xe.com/static-images/gmd.static.9850f582f710d4618606f289d3041eaa.svg", symbol: "GMD", sign: "GMD", describe: "Gambian Dalasi" },
    { logoURI: "https://www.xe.com/static-images/gnf.static.692b1bc8b9825cb184d2a5e2dca18145.svg", symbol: "GNF", sign: "GNF", describe: "Guinean Franc" },
    { logoURI: "https://www.xe.com/static-images/gtq.static.f32f9c0e8f517edaa9926e9274f57bbf.svg", symbol: "GTQ", sign: "GTQ", describe: "Guatemalan Quetzal" },
    { logoURI: "https://www.xe.com/static-images/gyd.static.012fe11cb8c9ce9d6ee4b01b5815f015.svg", symbol: "GYD", sign: "GYD", describe: "Guyanese Dollar" },
    { logoURI: "https://www.xe.com/static-images/hkd.static.58271e9b19cd7b99216124883951f4e4.svg", symbol: "HKD", sign: "HKD", describe: "Hong Kong Dollar" },
    { logoURI: "https://www.xe.com/static-images/hnl.static.cd822d4dd967c551fc6a923f9473d3bb.svg", symbol: "HNL", sign: "HNL", describe: "Honduran Lempira" },
    { logoURI: "https://www.xe.com/static-images/hrk.static.98403285496d4512cc0e47a7d93655e9.svg", symbol: "HRK", sign: "HRK", describe: "Croatian Kuna" },
    { logoURI: "https://www.xe.com/static-images/htg.static.d3a7bf362537fee36d765084fda11d0f.svg", symbol: "HTG", sign: "HTG", describe: "Haitian Gourde" },
    { logoURI: "https://www.xe.com/static-images/huf.static.92a71c7510cd256ec75a00cdc407e9fd.svg", symbol: "HUF", sign: "HUF", describe: "Hungarian Forint" },
    { logoURI: "https://www.xe.com/static-images/idr.static.178b9e1b023e72061512fb419f920d85.svg", symbol: "IDR", sign: "IDR", describe: "Indonesian Rupiah" },
    { logoURI: "https://www.xe.com/static-images/ils.static.9533154941ce97da2b7500ec5a36cf0c.svg", symbol: "ILS", sign: "ILS", describe: "Israeli Shekel" },
    { logoURI: "https://www.xe.com/static-images/imp.static.6ec126be21277d67f8cde9c5294704e1.svg", symbol: "IMP", sign: "IMP", describe: "Isle of Man Pound" },
    { logoURI: "https://www.xe.com/static-images/inr.static.9f6afce19e2f7f491c4d1d4faea36747.svg", symbol: "INR", sign: "INR", describe: "Indian Rupee" },
    { logoURI: "https://www.xe.com/static-images/iqd.static.7122d1a0f782cbd64bd7990d9b214de6.svg", symbol: "IQD", sign: "IQD", describe: "Iraqi Dinar" },
    { logoURI: "https://www.xe.com/static-images/irr.static.f3b57386bd6f808b3c64f8dccae21c04.svg", symbol: "IRR", sign: "IRR", describe: "Iranian Rial" },
    { logoURI: "https://www.xe.com/static-images/isk.static.e7b6f1ba61456aa5e5bd0d36ee5c28f3.svg", symbol: "ISK", sign: "ISK", describe: "Icelandic Krona" },
    { logoURI: "https://www.xe.com/static-images/jep.static.ff21c8385dfd6c8e72eb13de4d61ade8.svg", symbol: "JEP", sign: "JEP", describe: "Jersey Pound" },
    { logoURI: "https://www.xe.com/static-images/jmd.static.f35cad9f2676448497ff310d22b66fe3.svg", symbol: "JMD", sign: "JMD", describe: "Jamaican Dollar" },
    { logoURI: "https://www.xe.com/static-images/jod.static.429579ec0b0c70c2a040824f5c9a45d5.svg", symbol: "JOD", sign: "JOD", describe: "Jordanian Dinar" },
    { logoURI: "https://www.xe.com/static-images/jpy.static.238642084e415a2c2304c9b3da2308d9.svg", symbol: "JPY", sign: "JPY", describe: "Japanese Yen" },
    { logoURI: "https://www.xe.com/static-images/kes.static.295e9420565641397add4bd69173962b.svg", symbol: "KES", sign: "KES", describe: "Kenyan Shilling" },
    { logoURI: "https://www.xe.com/static-images/kgs.static.984d82699c406d3aa5d276621c958190.svg", symbol: "KGS", sign: "KGS", describe: "Kyrgyzstani Som" },
    { logoURI: "https://www.xe.com/static-images/khr.static.10cdd41602d2addef309baff5fac5433.svg", symbol: "KHR", sign: "KHR", describe: "Cambodian Riel" },
    { logoURI: "https://www.xe.com/static-images/kmf.static.388ecd98140f5f713811432165d6e501.svg", symbol: "KMF", sign: "KMF", describe: "Comorian Franc" },
    { logoURI: "https://www.xe.com/static-images/kpw.static.2c09ba2379b3e6b4d959f6c1b38e7eb7.svg", symbol: "KPW", sign: "KPW", describe: "North Korean Won" },
    { logoURI: "https://www.xe.com/static-images/krw.static.aa41e2dc026f804f874b2d8f851aefc5.svg", symbol: "KRW", sign: "KRW", describe: "South Korean Won" },
    { logoURI: "https://www.xe.com/static-images/kwd.static.d6c2b5cfa6e8626418dfa204f9c3ee20.svg", symbol: "KWD", sign: "KWD", describe: "Kuwaiti Dinar" },
    { logoURI: "https://www.xe.com/static-images/kyd.static.058bffc6e0530c2f6fbcfc7a9ddf67f0.svg", symbol: "KYD", sign: "KYD", describe: "Caymanian Dollar" },
    { logoURI: "https://www.xe.com/static-images/kzt.static.00587d26d1d9a67f4325cd42276ea651.svg", symbol: "KZT", sign: "KZT", describe: "Kazakhstani Tenge" },
    { logoURI: "https://www.xe.com/static-images/lak.static.f1ca04dc3297de6d9669b618c90d4afe.svg", symbol: "LAK", sign: "LAK", describe: "Lao Kip" },
    { logoURI: "https://www.xe.com/static-images/lbp.static.2bb077b89033ffb4b2d359063b70d6f8.svg", symbol: "LBP", sign: "LBP", describe: "Lebanese Pound" },
    { logoURI: "https://www.xe.com/static-images/lkr.static.1d7534a469ccaafe4c3eab40f187c676.svg", symbol: "LKR", sign: "LKR", describe: "Sri Lankan Rupee" },
    { logoURI: "https://www.xe.com/static-images/lrd.static.21aec31b4d2bce29a68207bef0ee58b3.svg", symbol: "LRD", sign: "LRD", describe: "Liberian Dollar" },
    { logoURI: "https://www.xe.com/static-images/lsl.static.664f5541b35775df3138564c5ec4d51c.svg", symbol: "LSL", sign: "LSL", describe: "Basotho Loti" },
    { logoURI: "https://www.xe.com/static-images/ltl.static.78d779b390c14f9e29ea2a9f924b3e2f.svg", symbol: "LTL", sign: "LTL", describe: "Lithuanian Litas" },
    { logoURI: "https://www.xe.com/static-images/lvl.static.7651261c8d56b2571c4b2b22aab4d59c.svg", symbol: "LVL", sign: "LVL", describe: "Latvian Lat" },
    { logoURI: "https://www.xe.com/static-images/lyd.static.739bd5a29841087a65f8398e906be86d.svg", symbol: "LYD", sign: "LYD", describe: "Libyan Dinar" },
    { logoURI: "https://www.xe.com/static-images/mad.static.2ca477326fc37322a2743bd30b2cd6ea.svg", symbol: "MAD", sign: "MAD", describe: "Moroccan Dirham" },
    { logoURI: "https://www.xe.com/static-images/mdl.static.f25f42cf12a20c81f77434eb49d825c3.svg", symbol: "MDL", sign: "MDL", describe: "Moldovan Leu" },
    { logoURI: "https://www.xe.com/static-images/mga.static.0515e1325b4b9d33d9ef41cfe169b687.svg", symbol: "MGA", sign: "MGA", describe: "Malagasy Ariary" },
    { logoURI: "https://www.xe.com/static-images/mkd.static.5874575d35b6cb3b4d0abcab7363de23.svg", symbol: "MKD", sign: "MKD", describe: "Macedonian Denar" },
    { logoURI: "https://www.xe.com/static-images/mmk.static.42cef00d393acc7cebab34c816743b28.svg", symbol: "MMK", sign: "MMK", describe: "Burmese Kyat" },
    { logoURI: "https://www.xe.com/static-images/mnt.static.6da2d4fbed25033c840755b21caa5cf1.svg", symbol: "MNT", sign: "MNT", describe: "Mongolian Tughrik" },
    { logoURI: "https://www.xe.com/static-images/mop.static.26780ccf71645057f447cf9561f87238.svg", symbol: "MOP", sign: "MOP", describe: "Macau Pataca" },
    { logoURI: "https://www.xe.com/static-images/mru.static.8dcb531f5eeea7232a9ef4e52c83c240.svg", symbol: "MRU", sign: "MRU", describe: "Mauritanian Ouguiya" },
    { logoURI: "https://www.xe.com/static-images/mur.static.2add1163461973562b28b17c86517321.svg", symbol: "MUR", sign: "MUR", describe: "Mauritian Rupee" },
    { logoURI: "https://www.xe.com/static-images/mvr.static.3d3d5a32155a91a07aa7ed68ad9f45ca.svg", symbol: "MVR", sign: "MVR", describe: "Maldivian Rufiyaa" },
    { logoURI: "https://www.xe.com/static-images/mwk.static.a1ed2110c5bb1936fd4b8c9f541d6283.svg", symbol: "MWK", sign: "MWK", describe: "Malawian Kwacha" },
    { logoURI: "https://www.xe.com/static-images/mxn.static.310a81ec23f9bab8efb18ae9ee9b3a05.svg", symbol: "MXN", sign: "MXN", describe: "Mexican Peso" },
    { logoURI: "https://www.xe.com/static-images/myr.static.f5e6382bf7c59e3ffac92149c96a383c.svg", symbol: "MYR", sign: "MYR", describe: "Malaysian Ringgit" },
    { logoURI: "https://www.xe.com/static-images/mzn.static.c5983c6a5c5dca148e573a5a23fd15a7.svg", symbol: "MZN", sign: "MZN", describe: "Mozambican Metical" },
    { logoURI: "https://www.xe.com/static-images/nad.static.9510d8526943bc81f2ae5924eb8725a7.svg", symbol: "NAD", sign: "NAD", describe: "Namibian Dollar" },
    { logoURI: "https://www.xe.com/static-images/ngn.static.b5060f1eed4a1656b5262e5f34fa92c8.svg", symbol: "NGN", sign: "NGN", describe: "Nigerian Naira" },
    { logoURI: "https://www.xe.com/static-images/nio.static.d5aea293b0d83bb86941b76edb9bcde6.svg", symbol: "NIO", sign: "NIO", describe: "Nicaraguan Cordoba" },
    { logoURI: "https://www.xe.com/static-images/nok.static.daea63143d627d7592d15d53ba70dd5f.svg", symbol: "NOK", sign: "NOK", describe: "Norwegian Krone" },
    { logoURI: "https://www.xe.com/static-images/npr.static.0478ea86d885861ec34577435760e72f.svg", symbol: "NPR", sign: "NPR", describe: "Nepalese Rupee" },
    { logoURI: "https://www.xe.com/static-images/nzd.static.7a4b8c0de7fdfd2f038c970f38bb3c10.svg", symbol: "NZD", sign: "NZD", describe: "New Zealand Dollar" },
    { logoURI: "https://www.xe.com/static-images/omr.static.9645a29f2292d23786b33abe40817cf5.svg", symbol: "OMR", sign: "OMR", describe: "Omani Rial" },
    { logoURI: "https://www.xe.com/static-images/pab.static.156acdf62f8be6b36520529e2548fe05.svg", symbol: "PAB", sign: "PAB", describe: "Panamanian Balboa" },
    { logoURI: "https://www.xe.com/static-images/pen.static.6c90430aead7579290fc0ce15fda079d.svg", symbol: "PEN", sign: "PEN", describe: "Peruvian Sol" },
    { logoURI: "https://www.xe.com/static-images/pgk.static.fbb456fc611384d7b7f482ec430b7480.svg", symbol: "PGK", sign: "PGK", describe: "Papua New Guinean Kina" },
    { logoURI: "https://www.xe.com/static-images/php.static.1e99a7e13fa0f9d28bd21405a107b9ab.svg", symbol: "PHP", sign: "PHP", describe: "Philippine Peso" },
    { logoURI: "https://www.xe.com/static-images/pkr.static.40871d6727f4a82f689a7082c2bbae80.svg", symbol: "PKR", sign: "PKR", describe: "Pakistani Rupee" },
    { logoURI: "https://www.xe.com/static-images/pln.static.9a46c60e77376605ebbcd2f2db735825.svg", symbol: "PLN", sign: "PLN", describe: "Polish Zloty" },
    { logoURI: "https://www.xe.com/static-images/pyg.static.df71b6481e047725ac6d9bb7f41eee1b.svg", symbol: "PYG", sign: "PYG", describe: "Paraguayan Guarani" },
    { logoURI: "https://www.xe.com/static-images/qar.static.c24ed06a965876b6d172ddb5262c5caa.svg", symbol: "QAR", sign: "QAR", describe: "Qatari Riyal" },
    { logoURI: "https://www.xe.com/static-images/ron.static.5191563aa4ed0531b4eabc8985f42a09.svg", symbol: "RON", sign: "RON", describe: "Romanian Leu" },
    { logoURI: "https://www.xe.com/static-images/rsd.static.bd9b361aebde444468f0a5c95ccef454.svg", symbol: "RSD", sign: "RSD", describe: "Serbian Dinar" },
    { logoURI: "https://www.xe.com/static-images/rub.static.273cd67a9958739d7c9e2fa98fe1e4f0.svg", symbol: "RUB", sign: "RUB", describe: "Russian Ruble" },
    { logoURI: "https://www.xe.com/static-images/rwf.static.0096a11e9f7213732b3103438ddac770.svg", symbol: "RWF", sign: "RWF", describe: "Rwandan Franc" },
    { logoURI: "https://www.xe.com/static-images/sar.static.172f85c044a4581c37da224739c18ecf.svg", symbol: "SAR", sign: "SAR", describe: "Saudi Arabian Riyal" },
    { logoURI: "https://www.xe.com/static-images/sbd.static.4dc06b107d35efe507a18f66eb88a8de.svg", symbol: "SBD", sign: "SBD", describe: "Solomon Islander Dollar" },
    { logoURI: "https://www.xe.com/static-images/scr.static.736246bb8079ad5e532d48d08fa6d2dc.svg", symbol: "SCR", sign: "SCR", describe: "Seychellois Rupee" },
    { logoURI: "https://www.xe.com/static-images/sdg.static.99f562fc2647ea3b67c11278a047d463.svg", symbol: "SDG", sign: "SDG", describe: "Sudanese Pound" },
    { logoURI: "https://www.xe.com/static-images/sek.static.cc692f6682dd03ca015c93f91e7ed2a3.svg", symbol: "SEK", sign: "SEK", describe: "Swedish Krona" },
    { logoURI: "https://www.xe.com/static-images/sgd.static.8088be44d3862b935a78268e9ac91159.svg", symbol: "SGD", sign: "SGD", describe: "Singapore Dollar" },
    { logoURI: "https://www.xe.com/static-images/shp.static.b82d39dd6233d17f04f1dc9b9bd254af.svg", symbol: "SHP", sign: "SHP", describe: "Saint Helenian Pound" },
    { logoURI: "https://www.xe.com/static-images/sll.static.c1338dc495cbd2e43fafd474842d6bff.svg", symbol: "SLL", sign: "SLL", describe: "Sierra Leonean Leone" },
    { logoURI: "https://www.xe.com/static-images/sos.static.ef567d7c3eee57ea04939cd1e1954094.svg", symbol: "SOS", sign: "SOS", describe: "Somali Shilling" },
    { logoURI: "https://www.xe.com/static-images/spl.static.7846e986c514672bab60b34916878967.svg", symbol: "SPL", sign: "SPL", describe: "Seborgan Luigino" },
    { logoURI: "https://www.xe.com/static-images/srd.static.c2b315981e3f62373381712eb48de866.svg", symbol: "SRD", sign: "SRD", describe: "Surinamese Dollar" },
    { logoURI: "https://www.xe.com/static-images/stn.static.e22587310ca74e4b43dc406edc65e9a7.svg", symbol: "STN", sign: "STN", describe: "Sao Tomean Dobra" },
    { logoURI: "https://www.xe.com/static-images/svc.static.0f4c206cf8da4ea820e51ad6dc4141e9.svg", symbol: "SVC", sign: "SVC", describe: "Salvadoran Colon" },
    { logoURI: "https://www.xe.com/static-images/syp.static.498928d8a792224f4a385410cbdbdc79.svg", symbol: "SYP", sign: "SYP", describe: "Syrian Pound" },
    { logoURI: "https://www.xe.com/static-images/szl.static.290947dd456f07221be2d3c60d3e9d8b.svg", symbol: "SZL", sign: "SZL", describe: "Swazi Lilangeni" },
    { logoURI: "https://www.xe.com/static-images/thb.static.ed0bb4147ff15361663a932b73f4dd70.svg", symbol: "THB", sign: "THB", describe: "Thai Baht" },
    { logoURI: "https://www.xe.com/static-images/tjs.static.8448fe56a6a500824558f7849d325a0d.svg", symbol: "TJS", sign: "TJS", describe: "Tajikistani Somoni" },
    { logoURI: "https://www.xe.com/static-images/tmt.static.0a5062f8c436c98d76fb740d6475d3da.svg", symbol: "TMT", sign: "TMT", describe: "Turkmenistani Manat" },
    { logoURI: "https://www.xe.com/static-images/tnd.static.32b431d78715647541882950082268dc.svg", symbol: "TND", sign: "TND", describe: "Tunisian Dinar" },
    { logoURI: "https://www.xe.com/static-images/top.static.9e723c2377e68251eb13efc5cd553c6b.svg", symbol: "TOP", sign: "TOP", describe: "Tongan Pa'anga" },
    { logoURI: "https://www.xe.com/static-images/try.static.e191946f81421814441cdc540d360060.svg", symbol: "TRY", sign: "TRY", describe: "Turkish Lira" },
    { logoURI: "https://www.xe.com/static-images/ttd.static.dccb12ae6ac404161d47303140afc752.svg", symbol: "TTD", sign: "TTD", describe: "Trinidadian Dollar" },
    { logoURI: "https://www.xe.com/static-images/tvd.static.135e18497a182352555dad4bd50ebfa9.svg", symbol: "TVD", sign: "TVD", describe: "Tuvaluan Dollar" },
    { logoURI: "https://www.xe.com/static-images/twd.static.f638b26f2ef82a943882eb3683797a09.svg", symbol: "TWD", sign: "TWD", describe: "Taiwan New Dollar" },
    { logoURI: "https://www.xe.com/static-images/tzs.static.13a052509ffb3334e34b3e29f740d9bb.svg", symbol: "TZS", sign: "TZS", describe: "Tanzanian Shilling" },
    { logoURI: "https://www.xe.com/static-images/uah.static.0c9644325e9eaed552249e212b0972c5.svg", symbol: "UAH", sign: "UAH", describe: "Ukrainian Hryvnia" },
    { logoURI: "https://www.xe.com/static-images/ugx.static.f92faf2ecc0220912b33175d69b6dabb.svg", symbol: "UGX", sign: "UGX", describe: "Ugandan Shilling" },
    { logoURI: "https://www.xe.com/static-images/usd.static.e8b657d1161a08a32415d284a8e1dc89.svg", symbol: "USD", sign: "USD", describe: "US Dollar" },
    { logoURI: "https://www.xe.com/static-images/uyu.static.add4e3977150637c7b5f457ab4d3a7f1.svg", symbol: "UYU", sign: "UYU", describe: "Uruguayan Peso" },
    { logoURI: "https://www.xe.com/static-images/uzs.static.a5b273e9fbda28dde90280cba614086f.svg", symbol: "UZS", sign: "UZS", describe: "Uzbekistani Som" },
    { logoURI: "https://www.xe.com/static-images/vef.static.a3fd5712833b768f51d1636c4356d055.svg", symbol: "VEF", sign: "VEF", describe: "Venezuelan Bolívar" },
    { logoURI: "https://www.xe.com/static-images/vnd.static.ba2c2151e5959cbd929d821f6e62d6cf.svg", symbol: "VND", sign: "VND", describe: "Vietnamese Dong" },
    { logoURI: "https://www.xe.com/static-images/vuv.static.1afee2c666fbf2ac0e059f1f743715cf.svg", symbol: "VUV", sign: "VUV", describe: "Ni-Vanuatu Vatu" },
    { logoURI: "https://www.xe.com/static-images/wst.static.e73a8831b69cd0b425b911ddb6d9d122.svg", symbol: "WST", sign: "WST", describe: "Samoan Tala" },
    { logoURI: "https://www.xe.com/static-images/xaf.static.7497c1983e48f8088eca5a39e1d9ad0d.svg", symbol: "XAF", sign: "XAF", describe: "Central African CFA Franc BEAC" },
    { logoURI: "https://www.xe.com/static-images/xag.static.378f69e2f5b90bb726dacbc653816b07.svg", symbol: "XAG", sign: "XAG", describe: "Silver Ounce" },
    { logoURI: "https://www.xe.com/static-images/xau.static.058bb2c8154ef1c26b66f26b887d4439.svg", symbol: "XAU", sign: "XAU", describe: "Gold Ounce" },
    { logoURI: "https://www.xe.com/static-images/xbt.static.3960772c018ef2bed762e3069a6db5ae.svg", symbol: "XBT", sign: "XBT", describe: "Bitcoin" },
    { logoURI: "https://www.xe.com/static-images/xcd.static.add8987f984512c94e9b1af2c2916f36.svg", symbol: "XCD", sign: "XCD", describe: "East Caribbean Dollar" },
    { logoURI: "https://www.xe.com/static-images/xdr.static.60e4b3a21fb9fc41c3a516587332e547.svg", symbol: "XDR", sign: "XDR", describe: "IMF Special Drawing Rights" },
    { logoURI: "https://www.xe.com/static-images/xof.static.10d4a3dc7bb8bbc4e2e65d33ce706bfd.svg", symbol: "XOF", sign: "XOF", describe: "CFA Franc" },
    { logoURI: "https://www.xe.com/static-images/xpd.static.3bd61a4e0500f39db8c1806bf6fdd40d.svg", symbol: "XPD", sign: "XPD", describe: "Palladium Ounce" },
    { logoURI: "https://www.xe.com/static-images/xpf.static.f14ed699466dae278166543510056bfa.svg", symbol: "XPF", sign: "XPF", describe: "CFP Franc" },
    { logoURI: "https://www.xe.com/static-images/xpt.static.5480db9bef8e43f298620eec5bc4afb4.svg", symbol: "XPT", sign: "XPT", describe: "Platinum Ounce" },
    { logoURI: "https://www.xe.com/static-images/yer.static.1d500b0e384ac0847d5111e0689bbfa2.svg", symbol: "YER", sign: "YER", describe: "Yemeni Rial" },
    { logoURI: "https://www.xe.com/static-images/zar.static.f78bb14b642f545ed8016b99235b0c88.svg", symbol: "ZAR", sign: "ZAR", describe: "South African Rand" },
    { logoURI: "https://www.xe.com/static-images/zmk.static.55eaea806877e79c3349cf90a550f1c9.svg", symbol: "ZMK", sign: "ZMK", describe: "Zambian Kwacha" },
    { logoURI: "https://www.xe.com/static-images/zmw.static.55eaea806877e79c3349cf90a550f1c9.svg", symbol: "ZMW", sign: "ZMW", describe: "Zambian Kwacha" },
    { logoURI: "https://www.xe.com/static-images/zwd.static.9535b6fcd130e3b3d8d3366f6519f6ec.svg", symbol: "ZWD", sign: "ZWD", describe: "Zimbabwean Dollar" },


]
export function AllFait(): FIAT[] {
    return ALLFIAT;
}
export function getFait(symbol: string): (FIAT | undefined) {
    let re: FIAT | undefined;
    ALLFIAT.forEach(element => {
        if (element.symbol === symbol) re = element;
    });
    return re

}




// const ssa = {
//     "USD": { "name": "US Dollar", "relatedTerms": ["United States Dollar", "America", "American Samoa", "American Virgin Islands", "British Indian Ocean Territory", "British Virgin Islands", "Ecuador", "El Salvador", "Guam", "Haiti", "Micronesia", "Northern Mariana Islands", "Palau", "Panama", "Puerto Rico", "Turks and Caicos Islands", "United States Minor Outlying Islands", "Wake Island", "East Timor"], "name_plural": "US Dollars" },
//     "EUR": { "name": "Euro", "relatedTerms": ["Euro Member Countries", "Andorra", "Austria", "Azores", "Baleares (Balearic Islands)", "Belgium", "Canary Islands", "Cyprus", "Finland", "France", "French Guiana", "French Southern Territories", "Germany", "Greece", "Guadeloupe", "Holland (Netherlands)", "Holy See (Vatican City)", "Ireland (Eire)", "Italy", "Luxembourg", "Madeira Islands", "Malta", "Monaco", "Montenegro", "Netherlands", "Portugal", "Réunion", "Saint Pierre and Miquelon", "Saint-Martin", "San Marino", "Slovakia", "Slovenia", "Spain", "Vatican City (The Holy See)", "Estonia", "Lithuania", "Latvia"], "name_plural": "Euros" },
//     "GBP": { "name": "British Pound", "relatedTerms": ["United Kingdom Pound", "UK", "England", "Northern Ireland", "Scotland", "Wales", "Falkland Islands", "Gibraltar", "Guernsey", "Isle of Man", "Jersey", "Saint Helena and Ascension", "South Georgia and the South Sandwich Islands", "Tristan da Cunha"], "name_plural": "British Pounds" },
//     "INR": { "name": "Indian Rupee", "relatedTerms": ["India Rupee", "Bhutan", "Nepal"], "name_plural": "Indian Rupees" },
//     "AUD": { "name": "Australian Dollar", "relatedTerms": ["Australia Dollar", "Christmas Island", "Cocos (Keeling) Islands", "Norfolk Island", "Ashmore and Cartier Islands", "Australian Antarctic Territory", "Coral Sea Islands", "Heard Island", "McDonald Islands", "Kiribati", "Nauru"], "name_plural": "Australian Dollars" },
//     "CAD": { "name": "Canadian Dollar", "relatedTerms": ["Canada Dollar"], "name_plural": "Canadian Dollars" },
//     "SGD": { "name": "Singapore Dollar", "relatedTerms": ["Singapore Dollar"], "name_plural": "Singapore Dollars" },
//     "CHF": { "name": "Swiss Franc", "relatedTerms": ["Switzerland Franc", "Liechtenstein", "Campione d'Italia", "Büsingen am Hochrhein"], "name_plural": "Swiss Francs" },
//     "MYR": { "name": "Malaysian Ringgit", "relatedTerms": ["Malaysia Ringgit"], "name_plural": "Malaysian Ringgits" },
//     "JPY": { "name": "Japanese Yen", "relatedTerms": ["Japan Yen"], "name_plural": "Japanese Yen" },
//     "CNY": { "name": "Chinese Yuan Renminbi", "relatedTerms": ["China Yuan Renminbi"], "name_plural": "Chinese Yuan Renminbi" },
//     "NZD": { "name": "New Zealand Dollar", "relatedTerms": ["New Zealand Dollar", "Cook Islands", "Niue", "Pitcairn Islands", "Tokelau"], "name_plural": "New Zealand Dollars" },
//     "THB": { "name": "Thai Baht", "relatedTerms": ["Thailand Baht"], "name_plural": "Thai Baht" },
//     "HUF": { "name": "Hungarian Forint", "relatedTerms": ["Hungary Forint"], "name_plural": "Hungarian Forints" },
//     "AED": { "name": "Emirati Dirham", "relatedTerms": ["United Arab Emirates Dirham"], "name_plural": "Emirati Dirhams" },
//     "HKD": { "name": "Hong Kong Dollar", "relatedTerms": ["Hong Kong Dollar"], "name_plural": "Hong Kong Dollars" },
//     "MXN": { "name": "Mexican Peso", "relatedTerms": ["Mexico Peso"], "name_plural": "Mexican Pesos" },
//     "ZAR": { "name": "South African Rand", "relatedTerms": ["South Africa Rand", "Lesotho", "Namibia"], "name_plural": "South African Rand" },
//     "PHP": { "name": "Philippine Peso", "relatedTerms": ["Philippines Peso"], "name_plural": "Philippine Pesos" },
//     "SEK": { "name": "Swedish Krona", "relatedTerms": ["Sweden Krona"], "name_plural": "Swedish Kronor" },
//     "IDR": { "name": "Indonesian Rupiah", "relatedTerms": ["Indonesia Rupiah", "East Timor"], "name_plural": "Indonesian Rupiahs" },
//     "SAR": { "name": "Saudi Arabian Riyal", "relatedTerms": ["Saudi Arabia Riyal"], "name_plural": "Saudi Arabian Riyals" },
//     "BRL": { "name": "Brazilian Real", "relatedTerms": ["Brazil Real"], "name_plural": "Brazilian Reais" },
//     "TRY": { "name": "Turkish Lira", "relatedTerms": ["Turkey Lira", "North Cyprus"], "name_plural": "Turkish Lire" },
//     "KES": { "name": "Kenyan Shilling", "relatedTerms": ["Kenya Shilling"], "name_plural": "Kenyan Shillings" },
//     "KRW": { "name": "South Korean Won", "relatedTerms": ["Korea (South) Won"], "name_plural": "South Korean Won" },
//     "EGP": { "name": "Egyptian Pound", "relatedTerms": ["Egypt Pound", "Gaza Strip"], "name_plural": "Egyptian Pounds" },
//     "IQD": { "name": "Iraqi Dinar", "relatedTerms": ["Iraq Dinar"], "name_plural": "Iraqi Dinars" },
//     "NOK": { "name": "Norwegian Krone", "relatedTerms": ["Norway Krone", "Bouvet Island", "Svalbard", "Jan Mayen", "Queen Maud Land", "Peter I Island"], "name_plural": "Norwegian Kroner" },
//     "KWD": { "name": "Kuwaiti Dinar", "relatedTerms": ["Kuwait Dinar"], "name_plural": "Kuwaiti Dinars" },
//     "RUB": { "name": "Russian Ruble", "relatedTerms": ["Russia Ruble", "Tajikistan"], "name_plural": "Russian Rubles" },
//     "DKK": { "name": "Danish Krone", "relatedTerms": ["Denmark Krone", "Faroe Islands", "Greenland"], "name_plural": "Danish Kroner" },
//     "PKR": { "name": "Pakistani Rupee", "relatedTerms": ["Pakistan Rupee"], "name_plural": "Pakistani Rupees" },
//     "ILS": { "name": "Israeli Shekel", "relatedTerms": ["Israel Shekel", "Palestinian Territories"], "name_plural": "Israeli New Shekels" },
//     "PLN": { "name": "Polish Zloty", "relatedTerms": ["Poland Zloty"], "name_plural": "Polish Zlotych" },
//     "QAR": { "name": "Qatari Riyal", "relatedTerms": ["Qatar Riyal"], "name_plural": "Qatari Rials" },
//     "XAU": { "name": "Gold Ounce", "relatedTerms": ["Gold"], "name_plural": "Gold Ounces" },
//     "OMR": { "name": "Omani Rial", "relatedTerms": ["Oman Rial"], "name_plural": "Omani Rials" },
//     "COP": { "name": "Colombian Peso", "relatedTerms": ["Colombia Peso"], "name_plural": "Colombian Pesos" },
//     "CLP": { "name": "Chilean Peso", "relatedTerms": ["Chile Peso"], "name_plural": "Chilean Pesos" },
//     "TWD": { "name": "Taiwan New Dollar", "relatedTerms": ["Taiwan New Dollar"], "name_plural": "Taiwan New Dollars" },
//     "ARS": { "name": "Argentine Peso", "relatedTerms": ["Argentina Peso", "Islas Malvinas"], "name_plural": "Argentine Pesos" },
//     "CZK": { "name": "Czech Koruna", "relatedTerms": ["Czech Republic Koruna"], "name_plural": "Czech Koruny" },
//     "VND": { "name": "Vietnamese Dong", "relatedTerms": ["Viet Nam Dong"], "name_plural": "Vietnamese Dongs" },
//     "MAD": { "name": "Moroccan Dirham", "relatedTerms": ["Morocco Dirham", "Western Sahara"], "name_plural": "Moroccan Dirhams" },
//     "JOD": { "name": "Jordanian Dinar", "relatedTerms": ["Jordan Dinar"], "name_plural": "Jordanian Dinars" },
//     "BHD": { "name": "Bahraini Dinar", "relatedTerms": ["Bahrain Dinar"], "name_plural": "Bahraini Dinars" },
//     "XOF": { "name": "CFA Franc", "relatedTerms": ["Communauté Financière Africaine (BCEAO) Franc", "Benin", "Burkina Faso", "Ivory Coast", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo"], "name_plural": "CFA Francs" },
//     "LKR": { "name": "Sri Lankan Rupee", "relatedTerms": ["Sri Lanka Rupee"], "name_plural": "Sri Lankan Rupees" },
//     "UAH": { "name": "Ukrainian Hryvnia", "relatedTerms": ["Ukraine Hryvnia"], "name_plural": "Ukrainian Hryvni" },
//     "NGN": { "name": "Nigerian Naira", "relatedTerms": ["Nigeria Naira"], "name_plural": "Nigerian Nairas" },
//     "TND": { "name": "Tunisian Dinar", "relatedTerms": ["Tunisia Dinar"], "name_plural": "Tunisian Dinars" },
//     "UGX": { "name": "Ugandan Shilling", "relatedTerms": ["Uganda Shilling"], "name_plural": "Ugandan Shillings" },
//     "RON": { "name": "Romanian Leu", "relatedTerms": ["Romania Leu"], "name_plural": "Romanian Lei" },
//     "BDT": { "name": "Bangladeshi Taka", "relatedTerms": ["Bangladesh Taka"], "name_plural": "Bangladeshi Takas" },
//     "PEN": { "name": "Peruvian Sol", "relatedTerms": ["Peru Sol"], "name_plural": "Peruvian Soles" },
//     "GEL": { "name": "Georgian Lari", "relatedTerms": ["Georgia Lari"], "name_plural": "Georgian Lari" },
//     "XAF": { "name": "Central African CFA Franc BEAC", "relatedTerms": ["Communauté Financière Africaine (BEAC) CFA Franc BEAC", "Cameroon", "Central African Republic", "Chad", "Congo/Brazzaville", "Equatorial Guinea", "Gabon"], "name_plural": "Central African Francs" }, "FJD": { "name": "Fijian Dollar", "relatedTerms": ["Fiji Dollar"], "name_plural": "Fijian Dollars" }, "VEF": { "name": "Venezuelan Bolívar", "relatedTerms": ["Venezuela Bolívar"], "name_plural": "Venezuelan Bolívares" }, "VES": { "name": "Venezuelan Bolívar", "relatedTerms": ["Venezuela Bolívar"], "name_plural": "Venezuelan Bolívares" }, "BYN": { "name": "Belarusian Ruble", "relatedTerms": ["Belarus Ruble"], "name_plural": "Belarusian Rubles" }, "HRK": { "name": "Croatian Kuna", "relatedTerms": ["Croatia Kuna"], "name_plural": "Croatian Kunas" }, "UZS": { "name": "Uzbekistani Som", "relatedTerms": ["Uzbekistan Som"], "name_plural": "Uzbekistani Sums" }, "BGN": { "name": "Bulgarian Lev", "relatedTerms": ["Bulgaria Lev"], "name_plural": "Bulgarian Leva" }, "DZD": { "name": "Algerian Dinar", "relatedTerms": ["Algeria Dinar"], "name_plural": "Algerian Dinars" }, "IRR": { "name": "Iranian Rial", "relatedTerms": ["Iran Rial"], "name_plural": "Iranian Rials" }, "DOP": { "name": "Dominican Peso", "relatedTerms": ["Dominican Republic Peso"], "name_plural": "Dominican Pesos" }, "ISK": { "name": "Icelandic Krona", "relatedTerms": ["Iceland Krona"], "name_plural": "Icelandic Kronur" }, "XAG": { "name": "Silver Ounce", "relatedTerms": ["Silver"], "name_plural": "Silver Ounces" }, "CRC": { "name": "Costa Rican Colon", "relatedTerms": ["Costa Rica Colon"], "name_plural": "Costa Rican Colones" }, "SYP": { "name": "Syrian Pound", "relatedTerms": ["Syria Pound"], "name_plural": "Syrian Pounds" }, "LYD": { "name": "Libyan Dinar", "relatedTerms": ["Libya Dinar"], "name_plural": "Libyan Dinars" }, "JMD": { "name": "Jamaican Dollar", "relatedTerms": ["Jamaica Dollar"], "name_plural": "Jamaican Dollars" }, "MUR": { "name": "Mauritian Rupee", "relatedTerms": ["Mauritius Rupee"], "name_plural": "Mauritian Rupees" }, "GHS": { "name": "Ghanaian Cedi", "relatedTerms": ["Ghana Cedi"], "name_plural": "Ghanaian Cedis" }, "AOA": { "name": "Angolan Kwanza", "relatedTerms": ["Angola Kwanza"], "name_plural": "Angolan Kwanzas" }, "UYU": { "name": "Uruguayan Peso", "relatedTerms": ["Uruguay Peso"], "name_plural": "Uruguayan Pesos" }, "AFN": { "name": "Afghan Afghani", "relatedTerms": ["Afghanistan Afghani"], "name_plural": "Afghan Afghanis" }, "LBP": { "name": "Lebanese Pound", "relatedTerms": ["Lebanon Pound"], "name_plural": "Lebanese Pounds" }, "XPF": { "name": "CFP Franc", "relatedTerms": ["Comptoirs Français du Pacifique (CFP) Franc", "French Polynesia", "New Caledonia", "Wallis and Futuna Islands"], "name_plural": "CFP Francs" }, "TTD": { "name": "Trinidadian Dollar", "relatedTerms": ["Trinidad and Tobago Dollar", "Trinidad", "Tobago"], "name_plural": "Trinidadian Dollars" }, "TZS": { "name": "Tanzanian Shilling", "relatedTerms": ["Tanzania Shilling"], "name_plural": "Tanzanian Shillings" }, "ALL": { "name": "Albanian Lek", "relatedTerms": ["Albania Lek"], "name_plural": "Albanian Leke" }, "XCD": { "name": "East Caribbean Dollar", "relatedTerms": ["East Caribbean Dollar", "Anguilla", "Antigua and Barbuda", "Dominica", "Grenada", "The Grenadines and Saint Vincent", "Montserrat"], "name_plural": "East Caribbean Dollars" }, "GTQ": { "name": "Guatemalan Quetzal", "relatedTerms": ["Guatemala Quetzal"], "name_plural": "Guatemalan Quetzales" }, "NPR": { "name": "Nepalese Rupee", "relatedTerms": ["Nepal Rupee", "India (unofficially near India-Nepal border)"], "name_plural": "Nepalese Rupees" }, "BOB": { "name": "Bolivian Bolíviano", "relatedTerms": ["Bolivia Bolíviano"], "name_plural": "Bolivian Bolivianos" }, "ZWD": { "name": "Zimbabwean Dollar", "relatedTerms": ["Zimbabwe Dollar"], "name_plural": "Zimbabwean Dollars" }, "BBD": { "name": "Barbadian or Bajan Dollar", "relatedTerms": ["Barbados Dollar"], "name_plural": "Barbadian or Bajan Dollars" }, "CUC": { "name": "Cuban Convertible Peso", "relatedTerms": ["Cuba Convertible Peso"], "name_plural": "Cuban Convertible Pesos" }, "LAK": { "name": "Lao Kip", "relatedTerms": ["Laos Kip"], "name_plural": "Lao Kips" }, "BND": { "name": "Bruneian Dollar", "relatedTerms": ["Brunei Darussalam Dollar"], "name_plural": "Bruneian Dollars" }, "BWP": { "name": "Botswana Pula", "relatedTerms": ["Botswana Pula"], "name_plural": "Botswana Pule" }, "HNL": { "name": "Honduran Lempira", "relatedTerms": ["Honduras Lempira"], "name_plural": "Honduran Lempiras" }, "PYG": { "name": "Paraguayan Guarani", "relatedTerms": ["Paraguay Guarani"], "name_plural": "Paraguayan Guarani" }, "ETB": { "name": "Ethiopian Birr", "relatedTerms": ["Ethiopia Birr", "Eritrea"], "name_plural": "Ethiopian Birrs" }, "NAD": { "name": "Namibian Dollar", "relatedTerms": ["Namibia Dollar"], "name_plural": "Namibian Dollars" }, "PGK": { "name": "Papua New Guinean Kina", "relatedTerms": ["Papua New Guinea Kina"], "name_plural": "Papua New Guinean Kina" }, "SDG": { "name": "Sudanese Pound", "relatedTerms": ["Sudan Pound"], "name_plural": "Sudanese Pounds" }, "MOP": { "name": "Macau Pataca", "relatedTerms": ["Macau Pataca"], "name_plural": "Macau Patacas" }, "NIO": { "name": "Nicaraguan Cordoba", "relatedTerms": ["Nicaragua Cordoba"], "name_plural": "Nicaraguan Cordobas" }, "BMD": { "name": "Bermudian Dollar", "relatedTerms": ["Bermuda Dollar"], "name_plural": "Bermudian Dollars" }, "KZT": { "name": "Kazakhstani Tenge", "relatedTerms": ["Kazakhstan Tenge"], "name_plural": "Kazakhstani Tenge" }, "PAB": { "name": "Panamanian Balboa", "relatedTerms": ["Panama Balboa"], "name_plural": "Panamanian Balboa" }, "BAM": { "name": "Bosnian Convertible Mark", "relatedTerms": ["Bosnia and Herzegovina Convertible Mark"], "name_plural": "Bosnian Convertible Marks" }, "GYD": { "name": "Guyanese Dollar", "relatedTerms": ["Guyana Dollar"], "name_plural": "Guyanese Dollars" }, "YER": { "name": "Yemeni Rial", "relatedTerms": ["Yemen Rial"], "name_plural": "Yemeni Rials" }, "MGA": { "name": "Malagasy Ariary", "relatedTerms": ["Madagascar Ariary"], "name_plural": "Malagasy Ariary" },
//     "KYD": { "name": "Caymanian Dollar", "relatedTerms": ["Cayman Islands Dollar"], "name_plural": "Caymanian Dollars" }, "MZN": { "name": "Mozambican Metical", "relatedTerms": ["Mozambique Metical"], "name_plural": "Mozambican Meticais" }, "RSD": { "name": "Serbian Dinar", "relatedTerms": ["Serbia Dinar"], "name_plural": "Serbian Dinars" }, "SCR": { "name": "Seychellois Rupee", "relatedTerms": ["Seychelles Rupee"], "name_plural": "Seychellois Rupees" }, "AMD": { "name": "Armenian Dram", "relatedTerms": ["Armenia Dram"], "name_plural": "Armenian Drams" }, "SBD": { "name": "Solomon Islander Dollar", "relatedTerms": ["Solomon Islands Dollar"], "name_plural": "Solomon Islander Dollars" }, "AZN": { "name": "Azerbaijan Manat", "relatedTerms": ["Azerbaijan Manat"], "name_plural": "Azerbaijan Manats" }, "SLL": { "name": "Sierra Leonean Leone", "relatedTerms": ["Sierra Leone Leone"], "name_plural": "Sierra Leonean Leones" }, "TOP": { "name": "Tongan Pa'anga", "relatedTerms": ["Tonga Pa'anga"], "name_plural": "Tongan Pa'anga" }, "BZD": { "name": "Belizean Dollar", "relatedTerms": ["Belize Dollar"], "name_plural": "Belizean Dollars" }, "MWK": { "name": "Malawian Kwacha", "relatedTerms": ["Malawi Kwacha"], "name_plural": "Malawian Kwachas" }, "GMD": { "name": "Gambian Dalasi", "relatedTerms": ["Gambia Dalasi"], "name_plural": "Gambian Dalasis" }, "BIF": { "name": "Burundian Franc", "relatedTerms": ["Burundi Franc"], "name_plural": "Burundian Francs" }, "SOS": { "name": "Somali Shilling", "relatedTerms": ["Somalia Shilling"], "name_plural": "Somali Shillings" }, "HTG": { "name": "Haitian Gourde", "relatedTerms": ["Haiti Gourde"], "name_plural": "Haitian Gourdes" }, "GNF": { "name": "Guinean Franc", "relatedTerms": ["Guinea Franc"], "name_plural": "Guinean Francs" }, "MVR": { "name": "Maldivian Rufiyaa", "relatedTerms": ["Maldives (Maldive Islands) Rufiyaa"], "name_plural": "Maldivian Rufiyaa" }, "MNT": { "name": "Mongolian Tughrik", "relatedTerms": ["Mongolia Tughrik"], "name_plural": "Mongolian Tugriks" }, "CDF": { "name": "Congolese Franc", "relatedTerms": ["Congo/Kinshasa Franc"], "name_plural": "Congolese Francs" }, "STN": { "name": "Sao Tomean Dobra", "relatedTerms": ["São Tomé and Príncipe Dobra"], "name_plural": "Sao Tomean Dobras" }, "TJS": { "name": "Tajikistani Somoni", "relatedTerms": ["Tajikistan Somoni"], "name_plural": "Tajikistani Somoni" }, "KPW": { "name": "North Korean Won", "relatedTerms": ["Korea (North) Won"], "name_plural": "North Korean Won" }, "MMK": { "name": "Burmese Kyat", "relatedTerms": ["Myanmar (Burma) Kyat"], "name_plural": "Burmese Kyats" }, "LSL": { "name": "Basotho Loti", "relatedTerms": ["Lesotho Loti"], "name_plural": "Basotho Maloti" }, "LRD": { "name": "Liberian Dollar", "relatedTerms": ["Liberia Dollar"], "name_plural": "Liberian Dollars" }, "KGS": { "name": "Kyrgyzstani Som", "relatedTerms": ["Kyrgyzstan Som"], "name_plural": "Kyrgyzstani Soms" }, "GIP": { "name": "Gibraltar Pound", "relatedTerms": ["Gibraltar Pound"], "name_plural": "Gibraltar Pounds" }, "XPT": { "name": "Platinum Ounce", "relatedTerms": ["Platinum"], "name_plural": "Platinum Ounces" }, "MDL": { "name": "Moldovan Leu", "relatedTerms": ["Moldova Leu"], "name_plural": "Moldovan Lei" }, "CUP": { "name": "Cuban Peso", "relatedTerms": ["Cuba Peso"], "name_plural": "Cuban Pesos" }, "KHR": { "name": "Cambodian Riel", "relatedTerms": ["Cambodia Riel"], "name_plural": "Cambodian Riels" }, "MKD": { "name": "Macedonian Denar", "relatedTerms": ["Macedonia Denar"], "name_plural": "Macedonian Denars" }, "VUV": { "name": "Ni-Vanuatu Vatu", "relatedTerms": ["Vanuatu Vatu"], "name_plural": "Ni-Vanuatu Vatu" }, "MRU": { "name": "Mauritanian Ouguiya", "relatedTerms": ["Mauritania Ouguiya"], "name_plural": "Mauritanian Ouguiyas" }, "ANG": { "name": "Dutch Guilder", "relatedTerms": ["Netherlands Antilles Guilder", "Bonaire", "Curaçao", "Saba", "Sint Eustatius", "Sint Maarten"], "name_plural": "Dutch Guilders (also called Florins)" }, "SZL": { "name": "Swazi Lilangeni", "relatedTerms": ["eSwatini Lilangeni"], "name_plural": "Swazi Emalangeni" }, "CVE": { "name": "Cape Verdean Escudo", "relatedTerms": ["Cape Verde Escudo"], "name_plural": "Cape Verdean Escudos" }, "SRD": { "name": "Surinamese Dollar", "relatedTerms": ["Suriname Dollar"], "name_plural": "Surinamese Dollars" }, "XPD": { "name": "Palladium Ounce", "relatedTerms": ["Palladium"], "name_plural": "Palladium Ounces" }, "SVC": { "name": "Salvadoran Colon", "relatedTerms": ["El Salvador Colon"], "name_plural": "Salvadoran Colones" }, "BSD": { "name": "Bahamian Dollar", "relatedTerms": ["Bahamas Dollar"], "name_plural": "Bahamian Dollars" }, "XDR": { "name": "IMF Special Drawing Rights", "relatedTerms": ["International Monetary Fund (IMF) Special Drawing Rights"], "name_plural": "IMF Special Drawing Rights" }, "RWF": { "name": "Rwandan Franc", "relatedTerms": ["Rwanda Franc"], "name_plural": "Rwandan Francs" }, "AWG": { "name": "Aruban or Dutch Guilder", "relatedTerms": ["Aruba Guilder"], "name_plural": "Aruban or Dutch Guilders (also called Florins)" }, "DJF": { "name": "Djiboutian Franc", "relatedTerms": ["Djibouti Franc"], "name_plural": "Djiboutian Francs" }, "BTN": { "name": "Bhutanese Ngultrum", "relatedTerms": ["Bhutan Ngultrum"], "name_plural": "Bhutanese Ngultrums" }, "KMF": { "name": "Comorian Franc", "relatedTerms": ["Comorian Franc"], "name_plural": "Comorian Francs" }, "WST": { "name": "Samoan Tala", "relatedTerms": ["Samoa Tala"], "name_plural": "Samoan Tala" }, "SPL": { "name": "Seborgan Luigino", "relatedTerms": ["Seborga Luigino"], "name_plural": "Seborgan Luigini" }, "ERN": { "name": "Eritrean Nakfa", "relatedTerms": ["Eritrea Nakfa"], "name_plural": "Eritrean Nakfas" }, "FKP": { "name": "Falkland Island Pound", "relatedTerms": ["Falkland Islands (Malvinas) Pound"], "name_plural": "Falkland Island Pounds" }, "SHP": { "name": "Saint Helenian Pound", "relatedTerms": ["Saint Helena Pound"], "name_plural": "Saint Helenian Pounds" }, "JEP": { "name": "Jersey Pound", "relatedTerms": ["Jersey Pound"], "name_plural": "Jersey Pounds" }, "TMT": { "name": "Turkmenistani Manat", "relatedTerms": ["Turkmenistan Manat"], "name_plural": "Turkmenistani Manats" }, "TVD": { "name": "Tuvaluan Dollar", "relatedTerms": ["Tuvalu Dollar"], "name_plural": "Tuvaluan Dollars" }, "IMP": { "name": "Isle of Man Pound", "relatedTerms": ["Isle of Man Pound"], "name_plural": "Isle of Man Pounds" }, "GGP": { "name": "Guernsey Pound", "relatedTerms": ["Guernsey Pound"], "name_plural": "Guernsey Pounds" }, "ZMW": { "name": "Zambian Kwacha", "relatedTerms": ["Zambia Kwacha"], "name_plural": "Zambian Kwacha" }, "XBT": { "name": "Bitcoin", "relatedTerms": ["BTC"], "name_plural": "Bitcoins" }, "FRF": { "name": "French Franc", "relatedTerms": ["France Franc"], "name_plural": "French Francs" }, "VEB": { "name": "Venezuelan Bolívar", "relatedTerms": ["Venezuela Bolívar"], "name_plural": "Venezuelan Bolívares" }, "ZMK": { "name": "Zambian Kwacha", "relatedTerms": ["Zambia Kwacha"], "name_plural": "Zambian Kwacha" }, "TRL": { "name": "Turkish Lira", "relatedTerms": ["Turkey Lira"], "name_plural": "Turkish Lira" }, "LVL": { "name": "Latvian Lat", "relatedTerms": ["Latvia Lat"], "name_plural": "Latvian Lati" }, "LTL": { "name": "Lithuanian Litas", "relatedTerms": ["Lithuania Litas"], "name_plural": "Lithuanian Litai" }, "EEK": { "name": "Estonian Kroon", "relatedTerms": ["Estonia Kroon"], "name_plural": "Estonian Krooni" }, "DEM": { "name": "German Deutsche Mark", "relatedTerms": ["Germany Deutsche Mark"], "name_plural": "German Deutsche Marks" }, "ROL": { "name": "Romanian Leu", "relatedTerms": ["Romania Leu"], "name_plural": "Romanian Lei" }, "STD": { "name": "Sao Tomean Dobra", "relatedTerms": ["São Tomé and Príncipe Dobra"], "name_plural": "Sao Tomean Dobras" }, "TMM": { "name": "Turkmenistani Manat", "relatedTerms": ["Turkmenistan Manat"], "name_plural": "Turkmenistani Manats" }, "ITL": { "name": "Italian Lira", "relatedTerms": ["Italy Lira"], "name_plural": "Italian Lire" }, "ESP": { "name": "Spanish Peseta", "relatedTerms": ["Spain Peseta"], "name_plural": "Spanish Pesetas" }, "MRO": { "name": "Mauritanian Ouguiya", "relatedTerms": ["Mauritania Ouguiya"], "name_plural": "Mauritanian Ouguiyas" }, "BEF": { "name": "Belgian Franc", "relatedTerms": ["Belgium Franc"], "name_plural": "Belgian Francs" }, "NLG": { "name": "Dutch Guilder", "relatedTerms": ["Netherlands Guilder"], "name_plural": "Dutch Guilders" }, "IEP": { "name": "Irish Pound", "relatedTerms": ["Ireland Pound"], "name_plural": "Irish Pounds" }, "CYP": { "name": "Cypriot Pound", "relatedTerms": ["Cyprus Pound"], "name_plural": "Cypriot Pounds" }, "SKK": { "name": "Slovak Koruna", "relatedTerms": ["Slovakia Koruna"], "name_plural": "Slovak Koruny" }, "MTL": { "name": "Maltese Lira", "relatedTerms": ["Malta Lira"], "name_plural": "Maltese Liri" }, "GRD": { "name": "Greek Drachma", "relatedTerms": ["Greece Drachma"], "name_plural": "Greek Drachmae" }, "PTE": { "name": "Portuguese Escudo", "relatedTerms": ["Portugal Escudo"], "name_plural": "Portuguese Escudos" }, "ATS": { "name": "Austrian Schilling", "relatedTerms": ["Austria Schilling"], "name_plural": "Austrian Schillings" }, "FIM": { "name": "Finnish Markka", "relatedTerms": ["Finland Markka"], "name_plural": "Finnish Markkaa" }, "SDD": { "name": "Sudanese Dinar", "relatedTerms": ["Sudan Dinar"], "name_plural": "Sudanese Dinars" }, "LUF": { "name": "Luxembourg Franc", "relatedTerms": ["Luxembourg Franc"], "name_plural": "Luxembourg Francs" }, "SRG": { "name": "Surinamese Guilder", "relatedTerms": ["Suriname Guilder"], "name_plural": "Surinamese Guilders" }, "SIT": { "name": "Slovenian Tolar", "relatedTerms": ["Slovenia Tolar"], "name_plural": "Slovenian Tolars" }, "GHC": { "name": "Ghanaian Cedi", "relatedTerms": ["Ghana Cedi"], "name_plural": "Ghanaian Cedis" }, "MZM": { "name": "Mozambican Metical", "relatedTerms": ["Mozambique Metical"], "name_plural": "Mozambican Meticais" },
//     "MGF": { "name": "Malagasy Franc", "relatedTerms": ["Madagascar Franc"], "name_plural": "Malagasy Francs" }, "AZM": { "name": "Azerbaijani Manat", "relatedTerms": ["Azerbaijan Manat"], "name_plural": "Azerbaijani Manats" }, "VAL": { "name": "Vatican City Lira", "relatedTerms": ["Vatican City Lira"], "name_plural": "Vatican City Lire" },
//     "BYR": { "name": "Belarusian Ruble", "relatedTerms": ["Belarus Ruble"], "name_plural": "Belarusian Rubles" }
// }
